trainer:
  max_epochs: 1000
  check_val_every_n_epoch: 1
  num_sanity_val_steps: 0
  precision: 16-mixed

  callbacks:
  - class_path: lightning.pytorch.callbacks.ModelCheckpoint
    init_args:
      every_n_epochs: 1
      save_top_k: 1
      monitor: "metrics/val_iou"
      mode: "max"
      save_last: true
      save_weights_only: true
  - class_path: lightning.pytorch.callbacks.EarlyStopping
    init_args:
      monitor: "metrics/val_iou"
      mode: "max"
      patience: 300
  - class_path: training.medical_val_logger.MedicalValLogger
    init_args:
      history_filename: "val_metrics_history.txt"
      best_filename: "best_metric.txt"
      monitor: "metrics/val_iou"

  logger:
    class_path: lightning.pytorch.loggers.CSVLogger
    init_args:
      save_dir: "runs"
      name: "isic2017_vit_query_mul_scale_fusion"

model:
  class_path: training.query_binary_mask_classification.QueryBinaryMaskClassification
  init_args:
    num_classes: 1
    img_size: [384, 384]
    ignore_idx: 255
    lr: 1e-4
    # weight_decay: 1e-2
    metric_threshold: 0.5

    network:
      class_path: models.eoseg.EoSegMultiQSegFusion
      init_args:
        num_classes: 1
        num_q: 2

        encoder:
          class_path: models.vit.ViT
          init_args:
            img_size: [384, 384]

data:
  class_path: datasets.isic_binary_semantic.ISICBinarySemantic
  init_args:
    train_image_dir: "datasets/ISIC-2017_Training_Data"
    train_mask_dir: "datasets/ISIC-2017_Training_Part1_GroundTruth"
    val_image_dir: "datasets/ISIC-2017_Test_v2_Data"
    val_mask_dir: "datasets/ISIC-2017_Test_v2_Part1_GroundTruth"
    test_image_dir: "datasets/ISIC-2017_Test_v2_Data"
    test_mask_dir: "datasets/ISIC-2017_Test_v2_Part1_GroundTruth"
    img_size: [384, 384]
    num_classes: 1
    batch_size: 8
    num_workers: 8
    ignore_idx: 255
    image_suffix: ".jpg"
    mask_suffix: "_segmentation.png"
